server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:h2:mem:PhoneBook  
    username: sa
    password:
    driverClassName: org.h2.Driver
    platform: h2
    
  h2:
    console:       enabled: true
      path: /h2-console
